/*
* Wire
* Copyright (C) 2025 Wire Swiss GmbH
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
* You should have received a copy of the GNU General Public License
* along with this program. If not, see http://www.gnu.org/licenses/.
*/

import { QualifiedId } from "./QualifiedId.js";
import { MessageEncryptionAlgorithm } from "./protobuf/MessageEncryptionAlgorithm.js";
import Long from "long";

const appUserId = process.env['WIRE_SDK_USER_ID']!
const appUserDomain = process.env['WIRE_SDK_USER_DOMAIN']!
const appQualifiedId = new QualifiedId(appUserId, appUserDomain)

export type Item = object

/**
 * Interface for message types to be extended from that can be used as Ephemeral(self-deleting) messages
 */
interface Ephemeral {
  expiresAfterMillis?: number | null
}

/**
 * Interface for message types to be extended from that can be used to reply
 */
interface Replyable {
  timestamp: Date
}

/**
 * Interface for message types to be extended from that can be edited
 */
interface Editable {
  replacingMessageId: string
}

export interface Mention {
  userId: QualifiedId
  offset: number
  length: number
}

export interface LinkPreview {
  urlOffset: number
  url: string
  permanentUrl?: string | null
  title?: string | null
  summary?: string | null
  image?: LinkPreviewAsset | null
}

export interface LinkPreviewAsset {
  mimeType: string
  metadata?: AssetMetadata | null
  assetDataPath?: string | null
  assetDataSize: number | Long
  assetHeight: number
  assetWidth: number
  assetName?: string | null
  assetKey?: string | null
  assetToken?: string | null
  assetDomain?: string | null
  otrKey: Uint8Array
  sha256Key: Uint8Array
  encryptionAlgorithm: MessageEncryptionAlgorithm
}

export interface WireMessageBase {
  type: string
  /**
   * Message ID, auto-generated by the SDK when sending or populated from the received event
   */
  id: string

  /**
   * Conversation ID where the message is sent/received
   */
  conversationId: QualifiedId

  /**
   * User/App that sent the message, useful when receiving messages, ignored(auto-populated) when sending messages
   */
  sender?: QualifiedId
}

export class Unknown implements WireMessageBase {
  get id(): string {
    throw new Error("Unknown message, no ID")
  }

  get conversationId(): QualifiedId {
    throw new Error("Unknown message, no conversation")
  }

  get sender(): QualifiedId {
    throw new Error("Unknown message, no sender")
  }

  get timestamp(): Date {
    throw new Error("Unknown message, no timestamp")
  }

  readonly type = "unknown" as const
}

export class Ignored implements WireMessageBase {
  get id(): string {
    throw new Error("Ignored message, no ID")
  }

  get conversationId(): QualifiedId {
    throw new Error("Ignored message, no conversation")
  }

  get sender(): QualifiedId {
    throw new Error("Ignored message, no sender")
  }

  get timestamp(): Date {
    throw new Error("Ignored message, no timestamp")
  }

  readonly type = "ignored" as const
}

export interface TextMessage extends WireMessageBase, Item, Ephemeral, Replyable {
  type: 'text'
  text: string
  quotedMessageId?: string | null
  quotedMessageSha256?: Uint8Array | null
  mentions?: Mention[]
  linkPreviews?: LinkPreview[]
  expiresAfterMillis?: number | null
}

export const TextMessage = {
  create(
    params: {
      messageId?: string
      conversationId: QualifiedId
      text: string
      mentions?: Mention[]
      linkPreviews?: LinkPreview[]
      senderId?: QualifiedId
      expiresAfterMillis?: number | null | undefined,
      timestamp?: Date
    }
  ): TextMessage {
    return {
      type: 'text',
      id: params.messageId ?? crypto.randomUUID(),
      conversationId: params.conversationId,
      sender: params.senderId ?? appQualifiedId,
      text: params.text,
      mentions: params.mentions ?? [],
      linkPreviews: params.linkPreviews ?? [],
      timestamp: params.timestamp ?? new Date(),
      expiresAfterMillis: params.expiresAfterMillis ?? null
    }
  }
}

export interface TextEditedMessage extends WireMessageBase, Editable {
  type: 'text-edited'
  text: string
  mentions?: Mention[]
  linkPreviews?: LinkPreview[]
}

export const TextEditedMessage = {
  create(
    params: {
      messageId?: string
      conversationId: QualifiedId
      replacingMessageId: string
      text: string
      mentions?: Mention[]
      linkPreviews?: LinkPreview[]
      senderId?: QualifiedId
    }
  ): TextEditedMessage {
    return {
      type: 'text-edited',
      id: params.messageId ?? crypto.randomUUID(),
      conversationId: params.conversationId,
      sender: params.senderId ?? appQualifiedId,
      replacingMessageId: params.replacingMessageId,
      text: params.text,
      mentions: params.mentions ?? [],
      linkPreviews: params.linkPreviews ?? [],
    }
  }
}

export interface AssetMessage extends WireMessageBase, Ephemeral, Replyable {
  type: 'asset'
  sizeInBytes: number | Long
  name?: string | null
  mimeType: string
  metadata?: AssetMetadata | null
  remoteData?: AssetRemoteData | null
}

export const AssetMessage = {
  create(
    params: {
      messageId?: string
      conversationId: QualifiedId
      sizeInBytes: number | Long
      name?: string | null
      mimeType: string
      metadata?: AssetMetadata | null
      remoteData?: AssetRemoteData | null
      senderId?: QualifiedId,
      expiresAfterMillis?: number | null | undefined,
      timestamp?: Date
    }
  ): AssetMessage {
    return {
      type: 'asset',
      id: params.messageId ?? crypto.randomUUID(),
      conversationId: params.conversationId,
      sender: params.senderId ?? appQualifiedId,
      timestamp: params.timestamp ?? new Date(),
      sizeInBytes: params.sizeInBytes,
      name: params.name ?? null,
      mimeType: params.mimeType,
      metadata: params.metadata ?? null,
      remoteData: params.remoteData ?? null,
      expiresAfterMillis: params.expiresAfterMillis ?? null
    }
  }
}

export type AssetMetadata = Image | Video | Audio

export interface Image {
  type: 'image'
  width: number
  height: number
}

export interface Video {
  type: 'video'
  width?: number
  height?: number
  durationMs?: number
}

export interface Audio {
  type: 'audio'
  durationMs?: number
  normalizedLoudness?: Uint8Array
}

export interface AssetRemoteData {
  otrKey: Uint8Array
  sha256: Uint8Array
  assetId: string
  assetToken?: string | null
  assetDomain: string
  encryptionAlgorithm?: MessageEncryptionAlgorithm | null
}

export interface CompositeButton extends Item {
  type: 'composite_button'
  id: string
  text: string
}

export const CompositeButton = {
  create(
    params: {
      text: string
      id?: string
    }
  ): CompositeButton {
    return {
      type: 'composite_button',
      id: params.id ?? crypto.randomUUID(),
      text: params.text
    }
  }
}

export interface CompositeButtonAction extends WireMessageBase {
  type: "composite_button_action"
  referenceMessageId: string
  buttonId: string
}

export const CompositeButtonAction = {
  create(
    params: {
      messageId: string
      conversationId: QualifiedId
      referenceMessageId: string
      buttonId: string,
      senderId?: QualifiedId
    }
  ): CompositeButtonAction {
    return {
      type: 'composite_button_action',
      id: params.messageId,
      conversationId: params.conversationId,
      buttonId: params.buttonId,
      referenceMessageId: params.referenceMessageId,
      sender: params.senderId ?? appQualifiedId
    }
  }
}

export interface CompositeButtonActionConfirmation extends WireMessageBase {
  type: "composite_button_action_confirmation"
  referenceMessageId: string
  buttonId: string | null
}

export const CompositeButtonActionConfirmation = {
  create(
    params: {
      messageId: string
      conversationId: QualifiedId
      referenceMessageId: string
      buttonId: string | null,
      senderId?: QualifiedId
    }
  ): CompositeButtonActionConfirmation {
    return {
      type: 'composite_button_action_confirmation',
      id: params.messageId,
      conversationId: params.conversationId,
      buttonId: params.buttonId,
      referenceMessageId: params.referenceMessageId,
      ...(params.senderId && { sender: params.senderId })
    }
  }
}

export interface CompositeMessage extends WireMessageBase {
  type: "composite"
  items: Item[]
}

export const CompositeMessage = {
  create(
    params: {
      messageId?: string
      conversationId: QualifiedId
      text?: string
      itemList: Item[],
      senderId?: QualifiedId
    }
  ): CompositeMessage {
    const textItem = params.text
      ? TextMessage.create({
        conversationId: params.conversationId,
        text: params.text
      })
      : null

    return {
      type: "composite",
      id: params.messageId ?? crypto.randomUUID(),
      conversationId: params.conversationId,
      items: [...(textItem ? [textItem] : []), ...params.itemList],
      sender: params.senderId ?? appQualifiedId
    }
  }
}

export interface CompositeEditedMessage extends WireMessageBase, Editable {
  type: 'composite-edited'
  items: Item[]
}

export const CompositeEditedMessage = {
  create(
    params: {
      messageId?: string
      conversationId: QualifiedId
      replacingMessageId: string,
      itemList: Item[],
      senderId?: QualifiedId
    }
  ): CompositeEditedMessage {
    return {
      type: 'composite-edited',
      id: params.messageId ?? crypto.randomUUID(),
      conversationId: params.conversationId,
      items: params.itemList,
      sender: params.senderId ?? appQualifiedId,
      replacingMessageId: params.replacingMessageId
    }
  }
}

export interface Ping extends WireMessageBase, Ephemeral {
  type: 'ping'
}

export const Ping = {
  create(
    params: {
      messageId?: string
      conversationId: QualifiedId
      expiresAfterMillis?: number | null | undefined,
      senderId?: QualifiedId
    }
  ): Ping {
    return {
      type: 'ping',
      id: params.messageId ?? crypto.randomUUID(),
      conversationId: params.conversationId,
      ...(params.senderId && { sender: params.senderId }),
      expiresAfterMillis: params.expiresAfterMillis ?? null
    }
  }
}

export interface Location extends WireMessageBase, Ephemeral, Replyable {
  type: 'location'
  latitude: number
  longitude: number
  name: string | null
  zoom: number | null
}

export const Location = {
  create(
    params: {
      messageId?: string
      conversationId: QualifiedId
      latitude: number
      longitude: number
      name?: string | null | undefined
      zoom?: number | null | undefined
      senderId?: QualifiedId,
      expiresAfterMillis?: number | null | undefined,
      timestamp?: Date
    }
  ): Location {
    return {
      type: 'location',
      id: params.messageId ?? crypto.randomUUID(),
      conversationId: params.conversationId,
      latitude: params.latitude,
      longitude: params.longitude,
      name: params.name ?? null,
      zoom: params.zoom ?? null,
      sender: params.senderId ?? appQualifiedId,
      timestamp: params.timestamp ?? new Date(),
      expiresAfterMillis: params.expiresAfterMillis ?? null
    }
  }
}

export interface DeletedMessage extends WireMessageBase {
  type: 'deleted'
  messageId: string
}

export const DeletedMessage = {
  create(
    params: {
      id?: string
      conversationId: QualifiedId
      messageId: string,
      senderId?: QualifiedId
    }
  ): DeletedMessage {
    return {
      type: 'deleted',
      id: params.id ?? crypto.randomUUID(),
      conversationId: params.conversationId,
      messageId: params.messageId,
      ...(params.senderId && { sender: params.senderId })
    }
  }
}

export const ReceiptType = {
  DELIVERED: "DELIVERED",
  READ: "READ"
} as const;

export type ReceiptType = typeof ReceiptType[keyof typeof ReceiptType];

export interface Receipt extends WireMessageBase {
  type: 'receipt'
  receiptType: ReceiptType
  messageIds: string[]
}

export const Receipt = {
  create(
    params: {
      id?: string
      conversationId: QualifiedId
      receiptType: ReceiptType
      messageIds: string[],
      senderId?: QualifiedId
    }
  ): Receipt {
    return {
      type: 'receipt',
      id: params.id ?? crypto.randomUUID(),
      conversationId: params.conversationId,
      receiptType: params.receiptType,
      messageIds: params.messageIds,
      sender: params.senderId ?? appQualifiedId
    }
  }
}

export interface Reaction extends WireMessageBase {
  type: 'reaction'
  messageId: string
  emojiSet: Set<string>
}

export const Reaction = {
  create(
    params: {
      id?: string
      conversationId: QualifiedId
      messageId: string
      emojiSet: Set<string>,
      senderId?: QualifiedId
    }
  ): Reaction {
    return {
      type: 'reaction',
      id: params.id ?? crypto.randomUUID(),
      conversationId: params.conversationId,
      messageId: params.messageId,
      emojiSet: params.emojiSet,
      ...(params.senderId && { sender: params.senderId })
    }
  }
}

export type WireMessage =
  | Unknown
  | Ignored
  | TextMessage
  | TextEditedMessage
  | AssetMessage
  | CompositeButtonAction
  | CompositeButtonActionConfirmation
  | CompositeMessage
  | CompositeEditedMessage
  | Ping
  | Location
  | DeletedMessage
  | Receipt
  | Reaction;
