/*
* Wire
* Copyright (C) 2025 Wire Swiss GmbH
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
* You should have received a copy of the GNU General Public License
* along with this program. If not, see http://www.gnu.org/licenses/.
*/

import { Ciphersuite, ClientId, ConversationId, CoreCrypto, CoreCryptoContext, CredentialType, DatabaseKey, GroupInfo, initWasmModule, Welcome } from "@wireapp/core-crypto";
import type { AppClientId } from "../model/AppClientId.js";
import { CoreCryptoMlsTransport } from "./CoreCryptoMlsTransport.js";
import type { MlsPublicKeys } from "../model/MlsPublicKeys.js";
import { PreKeyCrypto } from "../model/PreKeyCrypto.js";
import { Encoder } from "bazinga64";

export class CoreCryptoClient {
  private ciphersuite: Ciphersuite
  private mlsTransport: CoreCryptoMlsTransport
  private coreCrypto: CoreCrypto

  private constructor(
    ciphersuite: number,
    mlsTransport: CoreCryptoMlsTransport,
    coreCrypto: CoreCrypto
  ) {
    this.ciphersuite = ciphersuite
    this.mlsTransport = mlsTransport
    this.coreCrypto = coreCrypto
  }

  static async create(
    userId: string,
    ciphersuiteCode: number,
    cryptographyStoragePassword: string,
    mlsTransport: CoreCryptoMlsTransport
  ): Promise<CoreCryptoClient> {
    const uint8Array = new TextEncoder().encode(cryptographyStoragePassword);

    await initWasmModule("autogenerated/")
    const coreCrypto = await CoreCrypto.deferredInit({
      "databaseName": `${userId}`,
      "key": new DatabaseKey(uint8Array)
    })

    const coreCryptoClient = new CoreCryptoClient(
      this.getMlsCiphersuiteName(ciphersuiteCode),
      mlsTransport,
      coreCrypto
    )

    return coreCryptoClient
  }

  private static getMlsCiphersuiteName(ciphersuiteCode: number): Ciphersuite {
    switch (ciphersuiteCode) {
      case 1:
        return Ciphersuite.MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
      case 2:
        return Ciphersuite.MLS_128_DHKEMP256_AES128GCM_SHA256_P256
      case 3:
        return Ciphersuite.MLS_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519
      case 4:
        return Ciphersuite.MLS_256_DHKEMX448_AES256GCM_SHA512_Ed448
      case 5:
        return Ciphersuite.MLS_256_DHKEMP521_AES256GCM_SHA512_P521
      case 6:
        return Ciphersuite.MLS_256_DHKEMX448_CHACHA20POLY1305_SHA512_Ed448
      case 7:
        return Ciphersuite.MLS_256_DHKEMP384_AES256GCM_SHA384_P384
      default:
        return Ciphersuite.MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
    }
  }

  async initMlsClient(appClientId: AppClientId) {
    await this.coreCrypto.transaction(async (context) => {
      await context.mlsInit(
        new ClientId(new TextEncoder().encode(appClientId.value)),
        [this.ciphersuite]
      )
    })

    await this.coreCrypto.provideTransport(this.mlsTransport)
  }

  async mlsGenerateKeyPackages(): Promise<Uint8Array[]> {
    return await this.coreCrypto.transaction(async (context) => {
      return await context.clientKeypackages(
        this.ciphersuite,
        CredentialType.Basic,
        this.MLS_DEFAULT_KEYPACKAGE_COUNT
      )
    })
  }

  async getMlsPublicKey(): Promise<MlsPublicKeys> {
    const key = await this.coreCrypto.transaction(async (context) => {
      return await context.clientPublicKey(
        this.ciphersuite,
        CredentialType.Basic
      )
    })

    const encodedKey = Encoder.toBase64(key).asString

    switch (this.ciphersuite) {
      case Ciphersuite.MLS_128_DHKEMP256_AES128GCM_SHA256_P256:
        return { ecdsa_secp256r1_sha256: encodedKey };
  
      case Ciphersuite.MLS_256_DHKEMP384_AES256GCM_SHA384_P384:
        return { ecdsa_secp384r1_sha384: encodedKey };
  
      case Ciphersuite.MLS_256_DHKEMP521_AES256GCM_SHA512_P521:
        return { ecdsa_secp521r1_sha512: encodedKey };
  
      case Ciphersuite.MLS_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519:
      case Ciphersuite.MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519:
        return { ed25519: encodedKey };
  
      case Ciphersuite.MLS_256_DHKEMX448_AES256GCM_SHA512_Ed448:
      case Ciphersuite.MLS_256_DHKEMX448_CHACHA20POLY1305_SHA512_Ed448:
        // TODO: Map to WireException
        throw new Error("Unsupported ciphersuite")
  
      default:
        // TODO: Map to WireException
        throw new Error("Unknown ciphersuite");
    }
  }

  async initProteusClient() {
    await this.coreCrypto.transaction(async (context) => {
      await context.proteusInit()
    })
  }

  async generateProteusPreKeys(
    from: number = this.PROTEUS_PREKEYS_FROM_COUNT,
    count: number = this.PROTEUS_PREKEYS_MAX_COUNT
  ): Promise<PreKeyCrypto[]> {
    return await this.coreCrypto.transaction(async (context) => {
      const preKeys: PreKeyCrypto[] = await Promise.all(
        Array.from({ length: count }, async (__, index) => {
          const updatedIndex = from + index;
          const id = updatedIndex & 0xffff;
          const data = await context.proteusNewPrekey(id)
          
          return new PreKeyCrypto(id, Encoder.toBase64(data).asString);
        })
      )

      return preKeys
    })
  }

  async generateProteusLastPreKey(): Promise<PreKeyCrypto> {
    return await this.coreCrypto.transaction(async (context) => {
      const id = CoreCrypto.proteusLastResortPrekeyId()
      const data = await context.proteusLastResortPrekey()

      return new PreKeyCrypto(id, Encoder.toBase64(data).asString)
    })
  }

  async encryptMls(
    mlsGroupId: ConversationId,
    message: Uint8Array
  ): Promise<Uint8Array> {
    return await this.coreCrypto.transaction(async (context) => {
      return await context.encryptMessage(
        mlsGroupId,
        message
      )
    })
  }
  
  async decryptMls(
    mlsGroupId: ConversationId,
    encryptedMessageBytes: Uint8Array
  ): Promise<Uint8Array | undefined> {
    const decryptedMessage = await this.coreCrypto.transaction(async (context) => {
      return await context.decryptMessage(
        mlsGroupId,
        encryptedMessageBytes
      )
    })
    
    return decryptedMessage.message
  }

  async processWelcomeMessage(welcomeMessageBytes: Uint8Array) {
    await this.coreCrypto.transaction(async (context) => {
      await context.processWelcomeMessage(
        new Welcome(welcomeMessageBytes)
      )
    })
  }

  async hasTooFewKeyPackageCount(): Promise<boolean> {
    const packageCount = await this.coreCrypto.transaction(async (context) => {
      return await context.clientValidKeypackagesCount(this.ciphersuite, CredentialType.Basic)
    })
    return packageCount < this.MLS_DEFAULT_KEYPACKAGE_COUNT / 2
  }

  async conversationExists(mlsGroupId: ConversationId) {
    return await this.coreCrypto.transaction(async (context) => {
      return await context.conversationExists(mlsGroupId)
    })
  }

  async conversationEpoch(mlsGroupId: ConversationId) {
    return await this.coreCrypto.transaction(async (context) => {
      return await context.conversationEpoch(mlsGroupId)
    })
  }

  private async getCredentialType(context: CoreCryptoContext) {
    if (await context.e2eiIsEnabled(this.ciphersuite)) {
      return CredentialType.X509
    } else {
      return CredentialType.Basic
    }
  }

  async joinMlsConversationRequest(groupInfo: GroupInfo) {
    return await this.coreCrypto.transaction(async (context) => {
      const mlsCredentialType = await this.getCredentialType(context)
      return await context.joinByExternalCommit(
        groupInfo,
        mlsCredentialType
      )
    })
  }

  close() {
    return this.coreCrypto.close()
  }

  private PROTEUS_PREKEYS_FROM_COUNT: number = 0
  private PROTEUS_PREKEYS_MAX_COUNT: number = 10
  private MLS_DEFAULT_KEYPACKAGE_COUNT = 100
}