/*
* Wire
* Copyright (C) 2025 Wire Swiss GmbH
* 
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
* You should have received a copy of the GNU General Public License
* along with this program. If not, see http://www.gnu.org/licenses/.
*/

// Ciphersuite
import { Ciphersuite, ClientId, ConversationId, CoreCrypto, CredentialType, DatabaseKey, initWasmModule, Welcome } from "@wireapp/core-crypto";
import { Container, Service } from "typedi";
import { encodeBase64 } from "./../utils/Base64Util.js"
import { ClientsService } from "../api/ClientsService.js";
import { RegisterClientRequest } from "../api/request/RegisterClientRequest.js";
import { PreKeyCrypto } from "../model/PreKeyCrypto.js";
import { mapToPreKeyRequest } from "../mappers/PreKeyMapper.js";
import { CoreCryptoMlsTransport } from "./CoreCryptoMlsTransport.js";
import type { MlsPublicKeys } from "../model/MlsPublicKeys.js";
import { AppClientId } from "../model/AppClientId.js";
import { APP_CLIENT_ID, WIRE_USER_DOMAIN, WIRE_USER_ID, WIRE_USER_PASSWORD } from "../utils/DependencyInjectionTokens.js";
import { MlsService } from "../api/MlsService.js";
import { qualifiedIdToConversationId, type QualifiedId } from "../model/QualifiedId.js";

@Service()
export class CoreCryptoClient {
  userId: string
  ciphersuite: Ciphersuite
  coreCrypto: CoreCrypto

  private clientsService: ClientsService
  private mlsService: MlsService

  private constructor(
    userId: string,
    ciphersuite: Ciphersuite,
    coreCrypto: CoreCrypto,
    clientsService: ClientsService,
    mlsService: MlsService
  ) {
    this.userId = userId
    this.ciphersuite = ciphersuite
    this.coreCrypto = coreCrypto
    this.clientsService = clientsService
    this.mlsService = mlsService
  }

  static async create(
    userId: string,
    ciphersuiteCode: number,
    cryptographyStoragePassword: string
  ): Promise<CoreCryptoClient> {
    const clientsService = Container.get(ClientsService)
    const mlsService = Container.get(MlsService)
    const uint8Array = new TextEncoder().encode(cryptographyStoragePassword);

    await initWasmModule("autogenerated/")
    const coreCrypto = await CoreCrypto.deferredInit({
      "databaseName": `${userId}`,
      "key": new DatabaseKey(uint8Array)
    })

    const cryptoClient = new CoreCryptoClient(
      userId,
      this.getMlsCiphersuiteName(ciphersuiteCode),
      coreCrypto,
      clientsService,
      mlsService
    )

    return cryptoClient
  }

  async initOrRegisterClient() {
    // TODO: Once moved out of in-memory database, then verify for existing deviceId
    console.log("Initializing Proteus Client")
    await this.initProteusClient()
    const preKeys = await this.generateProteusPreKeys()
    const lastPreKey = await this.generateProteusLastPreKey()

    let clientResponse;
    try {
      const registerClientRequest = new RegisterClientRequest(
        Container.get<string>(WIRE_USER_PASSWORD),
        mapToPreKeyRequest(lastPreKey),
        preKeys.map((preKey) =>
          mapToPreKeyRequest(preKey)
        )
      )
      clientResponse = await this.clientsService.registerClient(registerClientRequest)
    } catch (error) {
      throw new Error(`Error when registering client: ${(error as Error).message}`);
    }

    const appClientId = AppClientId.create(
      Container.get<string>(WIRE_USER_ID),
      clientResponse.id,
      Container.get<string>(WIRE_USER_DOMAIN)
    )
    Container.set(APP_CLIENT_ID, appClientId)

    console.log("Initializing MLS Client")
    await this.initMlsClient(appClientId)
    await this.uploadClientWithMlsPublicKey()
    await this.uploadMlsKeyPackages()

    // TODO: setShouldRejoinConverastions(true) // only if its new client
  }

  private async initMlsClient(appClientId: AppClientId) {
    await this.coreCrypto.transaction(async (context) => {
      await context.mlsInit(
        new ClientId(new TextEncoder().encode(appClientId.value)),
        [this.ciphersuite]
      )
    })

    const mlsTransport: CoreCryptoMlsTransport = Container.get(CoreCryptoMlsTransport)
    await this.coreCrypto.provideTransport(mlsTransport)
  }

  private async uploadMlsKeyPackages() {
    const keyPackages = await this.mlsGenerateKeyPackages()
    await this.mlsService.uploadMlsKeyPackages(keyPackages)
  }

  public async mlsGenerateKeyPackages(): Promise<Uint8Array[]> {
    return await this.coreCrypto.transaction(async (context) => {
      return await context.clientKeypackages(
        this.ciphersuite,
        CredentialType.Basic,
        this.MLS_DEFAULT_KEYPACKAGE_COUNT
      )
    })
  }

  private async uploadClientWithMlsPublicKey() {
    const mlsPublicKeys = await this.getMlsPublicKey()
    await this.clientsService.updateClientWithMlsPublicKey(mlsPublicKeys)
  }

  private async getMlsPublicKey(): Promise<MlsPublicKeys> {
    const key = await this.coreCrypto.transaction(async (context) => {
      return await context.clientPublicKey(
        this.ciphersuite,
        CredentialType.Basic
      )
    })

    const encodedKey = encodeBase64(key)

    switch (this.ciphersuite) {
      case Ciphersuite.MLS_128_DHKEMP256_AES128GCM_SHA256_P256:
        return { ecdsa_secp256r1_sha256: encodedKey };
  
      case Ciphersuite.MLS_256_DHKEMP384_AES256GCM_SHA384_P384:
        return { ecdsa_secp384r1_sha384: encodedKey };
  
      case Ciphersuite.MLS_256_DHKEMP521_AES256GCM_SHA512_P521:
        return { ecdsa_secp521r1_sha512: encodedKey };
  
      case Ciphersuite.MLS_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519:
      case Ciphersuite.MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519:
        return { ed25519: encodedKey };
  
      case Ciphersuite.MLS_256_DHKEMX448_AES256GCM_SHA512_Ed448:
      case Ciphersuite.MLS_256_DHKEMX448_CHACHA20POLY1305_SHA512_Ed448:
        // TODO: Map to WireException
        throw new Error("Unsupported ciphersuite")
  
      default:
        // TODO: Map to WireException
        throw new Error("Unknown ciphersuite");
    }
  }

  private static getMlsCiphersuiteName(ciphersuiteCode: number): Ciphersuite {
    switch (ciphersuiteCode) {
      case 1:
        return Ciphersuite.MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
      case 2:
        return Ciphersuite.MLS_128_DHKEMP256_AES128GCM_SHA256_P256
      case 3:
        return Ciphersuite.MLS_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519
      case 4:
        return Ciphersuite.MLS_256_DHKEMX448_AES256GCM_SHA512_Ed448
      case 5:
        return Ciphersuite.MLS_256_DHKEMP521_AES256GCM_SHA512_P521
      case 6:
        return Ciphersuite.MLS_256_DHKEMX448_CHACHA20POLY1305_SHA512_Ed448
      case 7:
        return Ciphersuite.MLS_256_DHKEMP384_AES256GCM_SHA384_P384
      default:
        return Ciphersuite.MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519
    }
  }

  private async initProteusClient() {
    await this.coreCrypto.transaction(async (context) => {
      await context.proteusInit()
    })
  }

  private async generateProteusPreKeys(
    from: number = this.PROTEUS_PREKEYS_FROM_COUNT,
    count: number = this.PROTEUS_PREKEYS_MAX_COUNT
  ): Promise<PreKeyCrypto[]> {
    return await this.coreCrypto.transaction(async (context) => {
      const preKeys: PreKeyCrypto[] = await Promise.all(
        Array.from({ length: count }, async (__, index) => {
          const updatedIndex = from + index;
          const id = updatedIndex & 0xffff;
          const data = await context.proteusNewPrekey(id)
          
          return new PreKeyCrypto(id, encodeBase64(data));
        })
      )

      return preKeys
    })
  }

  private async generateProteusLastPreKey(): Promise<PreKeyCrypto> {
    return await this.coreCrypto.transaction(async (context) => {
      const id = CoreCrypto.proteusLastResortPrekeyId()
      const data = await context.proteusLastResortPrekey()

      return new PreKeyCrypto(id, encodeBase64(data))
    })
  }

  public async decryptMls(
    conversationId: QualifiedId,
    encryptedMessage: string
  ): Promise<Uint8Array | undefined> {
    // Decode base64 string to bytes
    const encryptedMessageBytes = Buffer.from(encryptedMessage, 'base64');
    const convId = qualifiedIdToConversationId(conversationId)
    
    // Decrypt the message using coreCrypto
    const decryptedMessage = await this.coreCrypto.transaction(async (it) => {
      return await it.decryptMessage(
        convId,
        encryptedMessageBytes
      );
    });
    
    return decryptedMessage.message;
  }

  public async encryptMls(
    conversationId: QualifiedId,
    message: Uint8Array
  ): Promise<Uint8Array> {
    return await this.coreCrypto.transaction(async (context) => {
      return await context.encryptMessage(
        qualifiedIdToConversationId(conversationId),
        message
      )
    })
  }

  public async processWelcomeMessage(welcomeMessageBytes: Uint8Array): Promise<ConversationId> {
    // TODO: re-join conversation if failed
    const welcomeBundle = await this.coreCrypto.transaction(async (context) => {
      return await context.processWelcomeMessage(
        new Welcome(welcomeMessageBytes)
      )
    })

    return welcomeBundle.id
  }

  public async hasTooFewKeyPackageCount(): Promise<boolean> {
    const packageCount = await this.coreCrypto.transaction(async (context) => {
      return await context.clientValidKeypackagesCount(this.ciphersuite, CredentialType.Basic)
    })
    return packageCount < this.MLS_DEFAULT_KEYPACKAGE_COUNT / 2
  }

  public async close() {
    await this.coreCrypto.close()
  }

  private PROTEUS_PREKEYS_FROM_COUNT: number = 0
  private PROTEUS_PREKEYS_MAX_COUNT: number = 10
  private MLS_DEFAULT_KEYPACKAGE_COUNT = 100
}
