name: Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: TypeScript Build
        run: npm run build

      - name: Build Sample
        run: npm run -w sample build

      - name: Tests with Coverage
        run: npm run test:coverage -- --no-cache

      - name: Packed Install Smoke Test
        run: npm run test:pack

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2.12.2
        with:
          json-summary-path: ./coverage/coverage-summary.json
          json-final-path: ./coverage/coverage-final.json

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: build-logs
          path: |
            build/
            eslint-report/
            coverage/
