name: Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v6.0.3
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typescript Build Setup
        run: npm run build:setup

      - name: TypeScript Build
        run: npm run build

      - name: Build Sample
        run: npm run build:sample

      - name: Tests with Coverage
        run: npm run test:coverage -- --no-cache

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2.12.0
        with:
          json-summary-path: ./coverage/coverage-summary.json
          json-final-path: ./coverage/coverage-final.json

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: build-logs
          path: |
            build/
            eslint-report/
            coverage/
